"""Domain enumerations aligned with docs/17, docs/34, docs/11."""

from __future__ import annotations

from enum import Enum


class RiskClass(str, Enum):
    PAYMENT_FAILURE = "PAYMENT_FAILURE"
    CHECKOUT_ABANDONMENT = "CHECKOUT_ABANDONMENT"
    SUBSCRIPTION_FAILURE = "SUBSCRIPTION_FAILURE"
    RECEIVABLE_OVERDUE = "RECEIVABLE_OVERDUE"
    MANDATE_HEALTH = "MANDATE_HEALTH"


class OpportunityState(str, Enum):
    DETECTED = "DETECTED"
    NOT_ADDRESSABLE = "NOT_ADDRESSABLE"
    DIAGNOSED = "DIAGNOSED"
    PRICED = "PRICED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    AUTHORISED = "AUTHORISED"
    ACTING = "ACTING"
    AWAITING_OUTCOME = "AWAITING_OUTCOME"
    RECONCILING = "RECONCILING"
    RECONCILIATION_FAILED = "RECONCILIATION_FAILED"
    DEFERRED = "DEFERRED"
    NO_ACTION_CYCLE = "NO_ACTION_CYCLE"
    RECOVERED = "RECOVERED"
    STOPPED = "STOPPED"
    CLOSED_UNRECOVERED = "CLOSED_UNRECOVERED"


class InterventionState(str, Enum):
    INTENDED = "INTENDED"
    IN_FLIGHT = "IN_FLIGHT"
    COMPLETED_SUCCESS = "COMPLETED_SUCCESS"
    COMPLETED_FAILED = "COMPLETED_FAILED"
    UNKNOWN = "UNKNOWN"
    RESOLVED_BY_RECONCILIATION = "RESOLVED_BY_RECONCILIATION"
    UNRESOLVED = "UNRESOLVED"


class ApprovalRequestState(str, Enum):
    QUEUED = "QUEUED"
    APPROVED = "APPROVED"
    APPROVED_MODIFIED = "APPROVED_MODIFIED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    VOIDED = "VOIDED"


class ReservationHandleState(str, Enum):
    HELD = "HELD"
    COMMITTED = "COMMITTED"
    RELEASED = "RELEASED"
    RECLAIMED = "RECLAIMED"


class CycleState(str, Enum):
    OPEN = "OPEN"
    DECIDING = "DECIDING"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    CLOSED = "CLOSED"
    ABORTED = "ABORTED"


class RunState(str, Enum):
    INITIALISED = "INITIALISED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    INVALIDATED = "INVALIDATED"
    ABORTED = "ABORTED"


class GateVerdictKind(str, Enum):
    ALLOW = "ALLOW"
    ALLOW_WITH_MODIFICATION = "ALLOW_WITH_MODIFICATION"
    DEFER = "DEFER"
    DENY = "DENY"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"


class ActionCode(str, Enum):
    """15 action codes from docs/11 §3."""

    A00 = "A00"  # NO_ACTION
    A01 = "A01"  # RETRY_PAYMENT_NOW
    A02 = "A02"  # RETRY_PAYMENT_SCHEDULED
    A03 = "A03"  # RETRY_DIFFERENT_INSTRUMENT
    A04 = "A04"  # SEND_PAYMENT_LINK
    A05 = "A05"  # SEND_REMINDER
    A06 = "A06"  # OFFER_INCENTIVE
    A07 = "A07"  # ESCALATE_TO_AGENT
    A08 = "A08"  # UPDATE_MANDATE
    A09 = "A09"  # RESUME_CHECKOUT
    A10 = "A10"  # PARTIAL_WRITE_OFF
    A11 = "A11"  # REQUEST_CONSENT
    A12 = "A12"  # DEFER_TO_NEXT_CYCLE
    A13 = "A13"  # CANCEL_AND_REISSUE
    A14 = "A14"  # MANUAL_REVIEW_ONLY


class DecisionOutcome(str, Enum):
    SELECTED = "SELECTED"
    NO_ACTION = "NO_ACTION"
    DEFERRED = "DEFERRED"
    STOPPED = "STOPPED"


class AttributionClass(str, Enum):
    ATTRIBUTED = "ATTRIBUTED"
    NATURAL = "NATURAL"
    AMBIGUOUS = "AMBIGUOUS"


class Observability(str, Enum):
    OBSERVED = "OBSERVED"
    UNOBSERVABLE = "UNOBSERVABLE"


class AgeingBucket(str, Enum):
    """Receivable ageing bands (RR-FUNC-008)."""

    D0_15 = "0-15"
    D16_30 = "16-30"
    D31_60 = "31-60"
    D61_90 = "61-90"
    D90_PLUS = "90+"


class NonAddressableReason(str, Enum):
    AMOUNT_NOT_DETERMINABLE = "AMOUNT_NOT_DETERMINABLE"
    ZERO_AMOUNT = "ZERO_AMOUNT"
    ANONYMOUS_CHECKOUT = "ANONYMOUS_CHECKOUT"
    ALREADY_SETTLED = "ALREADY_SETTLED"
    DISPUTED = "DISPUTED"
    WINDOW_EXPIRED = "WINDOW_EXPIRED"
    WRITTEN_OFF = "WRITTEN_OFF"


class CandidateAvailability(str, Enum):
    """M6 feasibility states — distinct from gate verdicts."""

    AVAILABLE = "AVAILABLE"
    INELIGIBLE = "INELIGIBLE"
    TEMPORARILY_UNAVAILABLE = "TEMPORARILY_UNAVAILABLE"
    IMPOSSIBLE = "IMPOSSIBLE"


class ConfidenceBand(str, Enum):
    """Diagnosis certainty bands — no numeric confidence on Diagnosis (docs/17 §4.2)."""

    LOW = "LOW"
    MED = "MED"
    HIGH = "HIGH"


class EvidenceKind(str, Enum):
    """Distinguish observed facts from inferred causes (M5)."""

    FACT = "FACT"
    PATTERN = "PATTERN"
    LIKELY_CAUSE = "LIKELY_CAUSE"
    UNKNOWN = "UNKNOWN"


class CauseCode(str, Enum):
    """Closed cause taxonomy — docs/12 §8.1. Never invent codes (RR-FUNC-011)."""

    CARD_EXPIRED = "CARD_EXPIRED"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    INSTRUMENT_BLOCKED = "INSTRUMENT_BLOCKED"
    INSTRUMENT_INVALID = "INSTRUMENT_INVALID"
    MANDATE_REVOKED = "MANDATE_REVOKED"
    MANDATE_EXPIRED = "MANDATE_EXPIRED"
    MANDATE_LIMIT_EXCEEDED = "MANDATE_LIMIT_EXCEEDED"
    MANDATE_NOT_PRESENTED = "MANDATE_NOT_PRESENTED"
    ISSUER_DECLINE_SOFT = "ISSUER_DECLINE_SOFT"
    ISSUER_DECLINE_HARD = "ISSUER_DECLINE_HARD"
    ISSUER_DOWNTIME = "ISSUER_DOWNTIME"
    ISSUER_RISK_DECLINE = "ISSUER_RISK_DECLINE"
    DO_NOT_HONOUR_AMBIGUOUS = "DO_NOT_HONOUR_AMBIGUOUS"
    AUTH_TIMEOUT = "AUTH_TIMEOUT"
    AUTH_ABANDONED_BY_CUSTOMER = "AUTH_ABANDONED_BY_CUSTOMER"
    SECOND_FACTOR_NOT_COMPLETED = "SECOND_FACTOR_NOT_COMPLETED"
    AUTH_SYSTEM_FAILURE = "AUTH_SYSTEM_FAILURE"
    GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT"
    GATEWAY_ERROR = "GATEWAY_ERROR"
    METHOD_UNAVAILABLE = "METHOD_UNAVAILABLE"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"
    PREFERRED_METHOD_NOT_OFFERED = "PREFERRED_METHOD_NOT_OFFERED"
    CHECKOUT_STEP_FRICTION = "CHECKOUT_STEP_FRICTION"
    PRICE_OR_FEE_HESITATION = "PRICE_OR_FEE_HESITATION"
    SESSION_INTERRUPTED = "SESSION_INTERRUPTED"
    INVOICE_NOT_RECEIVED = "INVOICE_NOT_RECEIVED"
    BUYER_APPROVAL_PENDING = "BUYER_APPROVAL_PENDING"
    QUERY_OR_DISPUTE_RAISED = "QUERY_OR_DISPUTE_RAISED"
    BUYER_CASHFLOW_CONSTRAINT = "BUYER_CASHFLOW_CONSTRAINT"
    OVERSIGHT_OR_FORGOTTEN = "OVERSIGHT_OR_FORGOTTEN"
    CUSTOMER_DECLINED_TO_PAY = "CUSTOMER_DECLINED_TO_PAY"
    ORDER_NO_LONGER_WANTED = "ORDER_NO_LONGER_WANTED"
    UNCLASSIFIED = "UNCLASSIFIED"


class SignalType(str, Enum):
    PAYMENT_ATTEMPT_FAILED = "PAYMENT_ATTEMPT_FAILED"
    PAYMENT_ATTEMPT_SUCCEEDED = "PAYMENT_ATTEMPT_SUCCEEDED"
    CHECKOUT_SESSION_ABANDONED = "CHECKOUT_SESSION_ABANDONED"
    INVOICE_ISSUED = "INVOICE_ISSUED"
    INVOICE_DUE = "INVOICE_DUE"
    INVOICE_PAID = "INVOICE_PAID"
    SUBSCRIPTION_CHARGE_FAILED = "SUBSCRIPTION_CHARGE_FAILED"
    MANDATE_STATE_CHANGED = "MANDATE_STATE_CHANGED"
    INSTRUMENT_STATE_CHANGED = "INSTRUMENT_STATE_CHANGED"
    REFUND_ISSUED = "REFUND_ISSUED"
    DISPUTE_OPENED = "DISPUTE_OPENED"
    WRITE_OFF = "WRITE_OFF"
    CUSTOMER_CONSENT_CHANGED = "CUSTOMER_CONSENT_CHANGED"
